language: go
go:
  - 1.10.1

before_install:
  - go get -t -v ./...

script:
  - go test github.com/nawazish-github/reactivator/observable -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash) 